name: Auto Create Branch
on:
    push:
    workflow_dispatch:
    schedule:
        - cron: '0 * * * *'
        - cron: '0 0 * * 1'
jobs:
    create:
        runs-on: ubuntu-latest
        env:
            PAT: ${{ secrets.PAT }}
        steps:
            - name: Get Code
              uses: actions/checkout@v3
              with:
                ref: main
            - name: Create date variable
              run: |
                next_thursday=$(date -d "next Thursday" +"%Y-%m-%d")
                echo "NEXT_THURSDAY=$next_thursday" >> $GITHUB_ENV
            - name: Use future date variable
              run: |
                echo "The future date is: $next_thursday"
            - name: Create branch and push
              run: |
                git config --global user.email "mohamed.samy.elshaar@gmail.com"
                git config --global user.name "Mohamed ElShaar"
                git checkout -b test-branch-$next_thursday
                git branch
                git remote set-url origin https://x-access-token:$PAT@github.com/mohamed-shaar/gh-variables.git
                git push --set-upstream origin test-branch-$next_thursday
