name: Auto Create Branch
on:
    workflow_dispatch:
    schedule:
        - cron: '0 * * * *'
        - cron: '0 0 * * 1'
jobs:
    create:
        runs-on: ubuntu-latest
        env:
            PAT: ${{ secrets.PAT }}
        steps:
            - name: Get Code
              uses: actions/checkout@v3
              with:
                ref: main
            - name: Create date variable
              run: |
                future_date=$(date -d "next Thursday" +"%Y-%m-%d")
                echo "FUTURE_DATE=$future_date" >> $GITHUB_ENV
            - name: Use future date variable
              run: |
                echo "The future date is: $FUTURE_DATE"
            - name: Create branch and push
              run: |
                git config --global user.email "mohamed.samy.elshaar@gmail.com"
                git config --global user.name "Mohamed ElShaar"
                git checkout -b test-branch-$FUTURE_DATE
                git branch
                git remote set-url origin https://x-access-token:$PAT@github.com/mohamed-shaar/gh-variables.git
                git push --set-upstream origin test-branch-$FUTURE_DATE
