name: Auto Create Branch
on:
    push:
    workflow_dispatch:
    schedule:
        - cron: '0 * * * *'
        - cron: '0 0 * * 1'
jobs:
    create:
        runs-on: ubuntu-latest
        env:
            GH_USERNAME: ${{secrets.GH_USERNAME}}
            GH_PASSWORD: ${{secrets.GH_PASSWORD}}
        steps:
            - name: Get Code
              uses: actions/checkout@v3
              with:
                ref: test-branch01
