name: Auto Create Branch
on:
    push:
    workflow_dispatch:
    schedule:
        - cron: '0 * * * *'
        - cron: '0 0 * * 1'
jobs:
    create:
        runs-on: ubuntu-latest
        env:
            GH_USERNAME: ${{secrets.GH_USERNAME}}
            GH_PASSWORD: ${{secrets.GH_PASSWORD}}
        steps:
            - name: Get Code
              uses: actions/checkout@v3
              with:
                ref: main
            - name: Create branch and push
              run: |
                git checkout -b test-branch
                git config user.name "github-actions[bot]"
                git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
                git push

