name: Call other workflows
on:
    workflow_dispatch:
    schedule:
        - cron: '*/5 * * * *'
jobs:
    call:
        runs-on: ubuntu-latest
        steps:
            - name: Invoke workflow without inputs
              uses: benc-uk/workflow-dispatch@v1
              with:
                workflow: deployment.yml