name: Call other workflows
on:
    workflow_dispatch:
    schedule:
        - cron: '*/5 * * * *'
jobs:
    call:
        runs-on: ubuntu-latest
        steps:
            - name: Call other workflow
              uses: actions/workflow-dispatch@v2
              with:
                workflow_id: deployment.yml